# Project: Calculator_C++
# Makefile created by Dev-C++ 5.4.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main_code.o add.o sub.o mult.o div.o
LINKOBJ  = main_code.o add.o sub.o mult.o div.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = Calculator_C++.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main_code.o: main_code.cpp
	$(CPP) -c main_code.cpp -o main_code.o $(CXXFLAGS)

add.o: add.cpp
	$(CPP) -c add.cpp -o add.o $(CXXFLAGS)

sub.o: sub.cpp
	$(CPP) -c sub.cpp -o sub.o $(CXXFLAGS)

mult.o: mult.cpp
	$(CPP) -c mult.cpp -o mult.o $(CXXFLAGS)

div.o: div.cpp
	$(CPP) -c div.cpp -o div.o $(CXXFLAGS)
